# 除外したい特定のパス（そのまま通常どおり配信）
[[redirects]]
  from = "/no-redirect"
  to = "/no-redirect"
  status = 200

[[redirects]]
  from = "/*"
  to = "https://github.com/ksk1015/astro-platform-starter"
  status = 301
  force = true